In [1]:
import torch 

In [3]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
x.shape

torch.Size([12])

In [7]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)
# dim=0 在列上拼接 

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

1. 矩阵的转置

In [13]:
A = torch.arange(20).reshape(5, 4)
print(A)
print(A.T)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])
tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])


Hadamard Product: A * B
范数：torch.norm()

In [14]:
a = torch.ones((2, 5, 4))
a.shape

torch.Size([2, 5, 4])

In [15]:
a.sum(axis=[0,2]).shape

torch.Size([5])

In [16]:
a.sum(axis=[0,2],keepdim=True).shape

torch.Size([1, 5, 1])

2. 对哪一维求和就是消除哪一维
3. torch不区分行向量和列向量吗？

In [17]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [18]:
x.requires_grad_(True)
x.grad

In [19]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [21]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [22]:
x.grad == 4 * x

tensor([True, True, True, True])

In [23]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])